/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author José Luis López
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Iniciar_Sesion = new javax.swing.JButton();
        Olvido_Contrasena = new javax.swing.JButton();
        Crear_Usuario = new javax.swing.JButton();
        Contrasena = new javax.swing.JTextField();
        Usuario = new javax.swing.JTextField();
        Marvel = new javax.swing.JLabel();
        Borde_Menu = new javax.swing.JLabel();
        Fondologin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1360, 760));
        setPreferredSize(new java.awt.Dimension(1360, 760));
        getContentPane().setLayout(null);

        Iniciar_Sesion.setBackground(new java.awt.Color(50, 130, 250));
        Iniciar_Sesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Iniciar_Sesion.setText("Iniciar sesión");
        getContentPane().add(Iniciar_Sesion);
        Iniciar_Sesion.setBounds(120, 360, 240, 45);

        Olvido_Contrasena.setBackground(new java.awt.Color(0, 0, 0));
        Olvido_Contrasena.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Olvido_Contrasena.setForeground(new java.awt.Color(255, 255, 255));
        Olvido_Contrasena.setText("¿Olvidaste tu contraseña?");
        Olvido_Contrasena.setBorder(null);
        getContentPane().add(Olvido_Contrasena);
        Olvido_Contrasena.setBounds(110, 420, 260, 45);

        Crear_Usuario.setBackground(new java.awt.Color(102, 255, 102));
        Crear_Usuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Crear_Usuario.setText("Crear cuenta nueva");
        getContentPane().add(Crear_Usuario);
        Crear_Usuario.setBounds(130, 500, 230, 45);

        Contrasena.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Contrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Contrasena.setText("Contraseña");
        getContentPane().add(Contrasena);
        Contrasena.setBounds(120, 290, 240, 45);

        Usuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Usuario.setText("Usuario");
        getContentPane().add(Usuario);
        Usuario.setBounds(120, 220, 240, 45);

        Marvel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/marvel.png"))); // NOI18N
        getContentPane().add(Marvel);
        Marvel.setBounds(110, 120, 280, 80);

        Borde_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Cuadrado_Bo.jpg"))); // NOI18N
        getContentPane().add(Borde_Menu);
        Borde_Menu.setBounds(70, 80, 350, 520);

        Fondologin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/guardianes_fondo_1.jpg"))); // NOI18N
        Fondologin.setMaximumSize(new java.awt.Dimension(1380, 768));
        Fondologin.setMinimumSize(new java.awt.Dimension(1380, 768));
        getContentPane().add(Fondologin);
        Fondologin.setBounds(0, 0, 1360, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Borde_Menu;
    public javax.swing.JTextField Contrasena;
    public javax.swing.JButton Crear_Usuario;
    public javax.swing.JLabel Fondologin;
    public javax.swing.JButton Iniciar_Sesion;
    private javax.swing.JLabel Marvel;
    public javax.swing.JButton Olvido_Contrasena;
    public javax.swing.JTextField Usuario;
    // End of variables declaration//GEN-END:variables
}
