/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Admin;

/**
 *
 * @author José Luis López
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Salir = new javax.swing.JButton();
        Persona = new javax.swing.JButton();
        Usuario = new javax.swing.JButton();
        Salir1 = new javax.swing.JButton();
        Salir2 = new javax.swing.JButton();
        Personaje = new javax.swing.JButton();
        Medio = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1040, 650));
        setPreferredSize(new java.awt.Dimension(1040, 650));
        getContentPane().setLayout(null);

        Salir.setBackground(new java.awt.Color(153, 204, 255));
        Salir.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        Salir.setText("Salir");
        getContentPane().add(Salir);
        Salir.setBounds(140, 480, 240, 35);

        Persona.setBackground(new java.awt.Color(153, 204, 255));
        Persona.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        Persona.setText("Persona");
        getContentPane().add(Persona);
        Persona.setBounds(140, 180, 240, 35);

        Usuario.setBackground(new java.awt.Color(153, 204, 255));
        Usuario.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        Usuario.setText("Usuario");
        getContentPane().add(Usuario);
        Usuario.setBounds(140, 240, 240, 35);

        Salir1.setBackground(new java.awt.Color(153, 204, 255));
        Salir1.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        Salir1.setText("Regresar");
        Salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir1ActionPerformed(evt);
            }
        });
        getContentPane().add(Salir1);
        Salir1.setBounds(140, 420, 110, 35);

        Salir2.setBackground(new java.awt.Color(153, 204, 255));
        Salir2.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        Salir2.setText("Siguiente");
        Salir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir2ActionPerformed(evt);
            }
        });
        getContentPane().add(Salir2);
        Salir2.setBounds(270, 420, 110, 35);

        Personaje.setBackground(new java.awt.Color(153, 204, 255));
        Personaje.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        Personaje.setText("Personaje");
        getContentPane().add(Personaje);
        Personaje.setBounds(140, 300, 240, 35);

        Medio.setBackground(new java.awt.Color(153, 204, 255));
        Medio.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        Medio.setText("Medio");
        getContentPane().add(Medio);
        Medio.setBounds(140, 360, 240, 35);

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel9.setText("¿Que desea hacer hoy?");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(110, 100, 300, 30);

        jLabel10.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel10.setText("Bienvenido Administrador");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 50, 350, 30);

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/Login Cruds.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1050, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Salir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Salir2ActionPerformed

    private void Salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Salir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Medio;
    public javax.swing.JButton Persona;
    public javax.swing.JButton Personaje;
    public javax.swing.JButton Salir;
    public javax.swing.JButton Salir1;
    public javax.swing.JButton Salir2;
    public javax.swing.JButton Usuario;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
